title: Rishi Yennu Fast Robots Website
description: My website for ECE 4160 Fast Robot Lab Writeups
theme: just-the-docs

url: https://rgtrio.github.io/RishiY-FastRobots/

aux_links:
  Github Repository: https://github.com/RGTrio/RishiY-FastRobots/
